management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  data:
    mongodb:
      url: '27017'
      auto-index-creation: 'true'
      database: mscard
      host: localhost
  application:
    name: ms-card
logging:
  level:
    '[com.nttdata.bootcamp.mscard]': info
server:
  port: '8084'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/
