server:
  port: 8089
spring:
  application:
    name: ms-discovery
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://ms-discovery:8089/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
logging:
  level:
    '[com.netflix.eureka]': 'OFF'
    '[com.netflix.discovery]': 'OFF'
    '[com.nttdata.bootcamp.msdiscovery]': Info
